create table public.purchases (

  id integer generated by default as identity not null,

  product_id integer not null,

  product_name character varying not null,

  quantity_ordered integer not null,

  supplier_name character varying null,

  supplier_email character varying null,

  status character varying null default 'pending'::character varying,

  message text null,

  created_at timestamp with time zone not null default timezone ('utc'::text, now()),

  constraint purchases_pkey primary key (id)

) TABLESPACE pg_default;





create table public.products (

  id integer generated by default as identity not null,

  product_name character varying not null,

  category character varying null,

  current_stock integer not null default 0,

  minimum_stock integer not null default 0,

  supplier_name character varying null,

  supplier_email character varying null,

  expiration_date date null,

  temperature numeric null,

  humidity numeric null,

  created_at timestamp with time zone not null default timezone ('utc'::text, now()),

  constraint products_pkey primary key (id)

) TABLESPACE pg_default;







create table public.stock_movements (

  id integer generated by default as identity not null,

  product_name character varying not null,

  movement_type character varying not null,

  quantity integer not null,

  reason text null,

  created_at timestamp with time zone not null default timezone ('utc'::text, now()),

  constraint stock_movements_pkey primary key (id),

  constraint stock_movements_movement_type_check check (

    (

      (movement_type)::text = any (

        (

          array['IN'::character varying, 'OUT'::character varying]

        )::text[]

      )

    )

  )

) TABLESPACE pg_default;







